### ISSUE TITLE
What exactly do the automatic repair?

### ISSUE THREAD

**Issue by BlueDrakoPT** [Foulest/RepairKit#5]
Deleting restrictive system policies ---> which ones?
Removing pre-installed bloatware ---> which ones?
Repairing the WMI repository - always? or only if it needs repairs?
Running registry, service, and settings tweaks - List of the tweaks?
Scanning for malware with Windows Defender - Where? All system? specific drive?

Please clarify. Thanks.

**Comment by Foulest** [comment]
The list of system policies that are deleted [can be found here](https://github.com/Foulest/RepairKit/blob/992fba09d9450f694a59d4a77c1fbb2366c20ce1/src/main/java/net/foulest/repairkit/panels/AutomaticRepairs.java#L245). The code deletes restrictive system policies that lock down Windows settings, features like Task Manager and Command Prompt, alongside restrictive Google Chrome settings. It also resets the registry values for the File Explorer and UAC.

The list of bloatware automatically removed [can be found here](https://github.com/Foulest/RepairKit/blob/992fba09d9450f694a59d4a77c1fbb2366c20ce1/src/main/java/net/foulest/repairkit/panels/AutomaticRepairs.java#L305). Pre-installed Windows applications like Candy Crush, Flipboard, and iHeartRadio are automatically removed, alongside otherwise useless apps like Bing News, Skype, and OneNote. A massive list of third-party publishers and their apps found on the Microsoft store are also removed.

The WMI repository is only repaired if it is found to be corrupted.

The full list of registry tweaks [can be found here](https://github.com/Foulest/RepairKit/blob/992fba09d9450f694a59d4a77c1fbb2366c20ce1/src/main/java/net/foulest/repairkit/panels/AutomaticRepairs.java#L680). It is rather exhaustive, but most functions are commented. A good portion of it is disabling Windows telemetry, patching security vulnerabilities, and other bloated features.

The full list of service tweaks [can be found here](https://github.com/Foulest/RepairKit/blob/992fba09d9450f694a59d4a77c1fbb2366c20ce1/src/main/java/net/foulest/repairkit/panels/AutomaticRepairs.java#L964). Unnecessary and telemetry-based services are disabled.

The full list of settings tweaks [can be found here](https://github.com/Foulest/RepairKit/blob/992fba09d9450f694a59d4a77c1fbb2366c20ce1/src/main/java/net/foulest/repairkit/panels/AutomaticRepairs.java#L1019). Everything is commented.

The Windows Defender section [can be found here](https://github.com/Foulest/RepairKit/blob/992fba09d9450f694a59d4a77c1fbb2366c20ce1/src/main/java/net/foulest/repairkit/panels/AutomaticRepairs.java#L1140). Aside from running a quick scan, a lot of hidden Windows Defender settings are applied to improve the protection level of Windows Defender. These settings have been thoroughly tested and verified as safe and non-intrusive.

Let me know if you have any more questions.

**Comment by BlueDrakoPT** [comment]
A big thank you for your patience in pointing all the info about your tool. Good work!
